### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by programad** [rocketclimb/.github#1]
- [x] Landing Page OK
 - [x] Docs Page OK
 - [x] Icons Page OK
 - [x] NPM Package published
 - [x] Github Sponsor
 - [x] rocketclimb/rocketicons#31 - https://www.patreon.com/rocketclimb
 - [x] Create Discord Server - https://discord.gg/58NguZ5ZEX
 - [x] rocketclimb/rocketicons#37
 - [x] X Account rocketclimb/rocketicons#36 - https://twitter.com/rocketclimb
 - [x] rocketclimb/rocketicons#27 
 - [x] rocketclimb/rocketicons#21 
 - [x] indiehackerstacks.com
 - [x] Reddit post
 - [ ] Take a look at [Vercel Launch checklist](https://vercel.com/docs/production-checklist)
 - [ ] Review sponsor tiers
